baseURL = "https://chrispeoples.com/"
title = "Chris Peoples"
theme = "noteworthy"
summaryLength = 10 # Configure how long the post summary should be on the homepage.
mainSections = ['post'] # Configure which sections show on homepage
enableGitInfo = true

[languages.en]
locale = "en-US"

# Set the number of posts to show before overflowing to the next page.
[pagination]
    pagerSize = 8


# Social media icons
[params]
    github = "https://github.com/chrisofspades"
    stackoverflow = "https://stackoverflow.com/users/2614/chrisofspades"
    linkedin = "http://www.linkedin.com/in/chrisofspades"
    archiveSections = ['post'] # Configure which sections show on archives

[markup.goldmark.renderer]
    unsafe = true

[frontmatter]
    lastmod = [':git', 'lastmod', 'modified', 'date', 'publishdate', 'pubdate', 'published']