name: Deploy via FTP

on:
  push:
    branches:
    - master
  schedule:
    - cron:  '0 8 * * *'
  repository_dispatch:
    types: manual-trigger

jobs:
  Build:
    runs-on: macos-latest
    steps:

    - uses: actions/checkout@v1
      with:
        submodules: true

    - name: Setup Hugo
      uses: peaceiris/actions-hugo@v2
      with:
        hugo-version: 'latest'
        extended: true

    - name: Build site
      run: hugo --minify
      
    - name: Upload build files
      uses: actions/upload-artifact@v2
      with:
        path: public/

  Deploy:
    runs-on: ubuntu-latest
    needs: [Build]
    steps:
      - uses: actions/checkout@v1
        with:
          submodules: true

      - name: Download build files
        uses: actions/download-artifact@v2

      - name: FTP site
        uses: SamKirkland/FTP-Deploy-Action@3.1.1
        with:
          ftp-server: sftp://ftp.chrispeoples.com/home/chrispeoples/chrispeoples.com/
          ftp-username: chrispeoples
          ftp-password: ${{ secrets.FTP_PASSWORD }}
          local-dir: artifact/
          git-ftp-args: --insecure --all
